sonar.projectKey=RandomCodeSpace_code-iq-java
sonar.organization=randomcodespace
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.source=25
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/grammar/**,target/generated-sources/**
