#!/usr/bin/env bash
# Build BASELINE.md from captured raw/ artifacts. Idempotent; safe to re-run.
set -euo pipefail
RAW="docs/superpowers/baselines/2026-04-17/raw"
OUT="docs/superpowers/baselines/2026-04-17/BASELINE.md"

read_json() { [[ -f "$1" ]] && cat "$1" || echo "null"; }

TESTS=$(read_json "$RAW/test-counts.json")
COV=$(read_json   "$RAW/coverage-summary.json")
FLAKY=$(read_json "$RAW/flaky.json")
SB=$(read_json    "$RAW/spotbugs-summary.json")
DC=$(read_json    "$RAW/depcheck-summary.json")
FRONT_PW=$(read_json "$RAW/frontend/playwright-summary.json")
PL_PC=$(read_json "$RAW/pipeline/spring-petclinic/summary.json")
PL_RW=$(read_json "$RAW/pipeline/realworld-express/summary.json")

JAVA_V=$(java -version 2>&1 | head -n1)
MVN_V=$(mvn -v 2>&1 | head -n1)
NODE_V=$(node --version)
NPM_V=$(npm --version)

cat > "$OUT" <<MD
# code-iq Baseline — 2026-04-17

This file is generated by \`scripts/baseline/consolidate.sh\`. Re-run after
updating any capture script. Raw artifacts under \`raw/\` are gitignored.

## Toolchain

- Java: $JAVA_V
- Maven: $MVN_V
- Node: $NODE_V
- npm: $NPM_V

## Maven build & tests

\`\`\`json
$TESTS
\`\`\`

## Coverage (JaCoCo)

\`\`\`json
$COV
\`\`\`

## Flaky tests

\`\`\`json
$FLAKY
\`\`\`

## SpotBugs

\`\`\`json
$SB
\`\`\`

## OWASP dependency-check

\`\`\`json
$DC
\`\`\`

## Frontend

- Playwright:
\`\`\`json
$FRONT_PW
\`\`\`
- Full logs: \`raw/frontend/\` (local only).

## Pipeline on seed repos

### spring-petclinic
\`\`\`json
$PL_PC
\`\`\`

### realworld-express
\`\`\`json
$PL_RW
\`\`\`

## Known gaps / issues

Populate this section manually after reading the raw outputs. Examples to
look for: failing tests, flaky set non-empty, SpotBugs HIGH priority bugs,
CVEs ≥ CRITICAL, coverage hot spots.
MD
echo "Wrote $OUT"
