"""Protocol definitions for graph storage backends."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from osscodeiq.models.graph import (
    EdgeKind,
    GraphEdge,
    GraphNode,
    NodeKind,
)


@runtime_checkable
class GraphBackend(Protocol):
    """Contract that every graph storage backend must satisfy."""

    def add_node(self, node: GraphNode) -> None: ...
    def add_edge(self, edge: GraphEdge) -> None: ...
    def clear(self) -> None: ...
    def get_node(self, node_id: str) -> GraphNode | None: ...
    def has_node(self, node_id: str) -> bool: ...
    def get_edges_between(self, source: str, target: str) -> list[GraphEdge]: ...
    def all_nodes(self) -> list[GraphNode]: ...
    def all_edges(self) -> list[GraphEdge]: ...
    def nodes_by_kind(self, kind: NodeKind) -> list[GraphNode]: ...
    def edges_by_kind(self, kind: EdgeKind) -> list[GraphEdge]: ...

    @property
    def node_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...

    def neighbors(
        self, node_id: str,
        edge_kinds: set[EdgeKind] | None = None,
        direction: str = "both",
    ) -> list[str]: ...

    def find_cycles(self, limit: int = 100) -> list[list[str]]: ...
    def shortest_path(self, source: str, target: str) -> list[str] | None: ...
    def subgraph(self, node_ids: set[str]) -> GraphBackend: ...
    def update_node_properties(self, node_id: str, properties: dict[str, Any]) -> None: ...
    def close(self) -> None: ...


@runtime_checkable
class CypherBackend(Protocol):
    """Optional capability for backends supporting Cypher queries."""

    def query_cypher(self, cypher: str, params: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...
